name: Hello world workflow 

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  issues: 
    types: [opened, edited]
    

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user 
        run: echo "Hello world!"
      - run: ls -l
      - uses: actions/checkout@v4
      - run: ls -l

